name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: NPM
        run: |
<<<<<<< HEAD
          npm install -g npm@6  
          npm ci
=======
          npm ci
          rm package-lock.json
          npm install
>>>>>>> 919a57f0a5ef1a67a1230652f1e933297dc51fc0
          npm -v
          node -v

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: conf.json
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
