name: Tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: NPM
      run: |
        npm -v
        node -v
    
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3

    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src
        recurse: true
        output_dir: ./out

    - name: Commit files and push
      run: |
        git config --local user.email "jid001@ucsd.edu"
        git config --local user.name "Jiayan Dong"
        git remote set-url origin https://x-access-token:${{ secrets.PUSH_KEY }}@github.com/${{ github.repository }}
        git add out
        git commit -m "JSDOC"
        git push
