name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src
        recurse: true
        output_dir: ./out

    - name: Commit files
      run: |
        git config --local user.email "jid001@ucsd.edu"
        git config --local user.name "Jiayan Dong"
        git add out
        git commit -m "JSDOC"

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
