name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src
        recurse: true
        output_dir: ./out

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0

    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
